### ISSUE TITLE
Overview plot of max depth per profile

### ISSUE THREAD

**Issue by eleanorfrajka** [OceanGlidersCommunity/glidertest#146]
This will be an overview plot of either histogram or time series (or other). that extracts the maximum pressure for each PROFILE_NUMBER and then visualises it.

**Comment by tillmrtz** [comment]
Hey I can actually comment

**Comment by callumrollo** [comment]
Sounds cool! Don't forget this repo is migrating over to Ocean Gliders Community today! Expect some disruption

https://github.com/OceanGlidersCommunity
