### ISSUE TITLE
[docs] Update CITATION.cff for new repository location 

### ISSUE THREAD

**Issue by eleanorfrajka** [OceanGlidersCommunity/glidertest#158]
Is CITATION.cff supposed to be updated every time there is a release?

Currently says:
```
version: 0.0.1
date-released: 2024-10-28
url: https://github.com/callumrollo/glidertest
```

**Comment by callumrollo** [comment]
Yes, we should do that. It will also remind us to add new contributors and in this case update the url

**Comment by LouClement** [comment]
Thank you Chiara, that looks good.
